ALTER TABLE THANHVIEN
ADD CONSTRAINT Check_YEAR CHECK ( YEAR([NGAYTG]) > YEAR([NGSINH]))

ALTER TABLE THANHVIEN
ADD CONSTRAINT Check_GMAIL CHECK (GMAIL LIKE '%_@%.%')

ALTER TABLE THANHVIEN
ADD CONSTRAINT Check_SDT_TV CHECK (LEN(SDT)=10 AND (SDT LIKE '0%' ))
-- bảng NVIENVC
ALTER TABLE NVIENVC
ADD CONSTRAINT Check_SDT_NVVC CHECK (LEN(SDT)=10 AND (SDT LIKE '0%' ))
--bảng SANPHAM
ALTER TABLE SANPHAM
ADD CONSTRAINT Check_GIA CHECK ( GIA > 0)
--bảng VOUCHERSHOP
ALTER TABLE VoucherSHOP
ADD CONSTRAINT Check_GIATRI CHECK (GIATRI>0)
--bảng DONHANG
ALTER TABLE DONHANG
ADD CONSTRAINT Check_SDT_DH CHECK (LEN(SDT)=10 AND (SDT LIKE '0%' ))

ALTER TABLE DONHANG
ADD CONSTRAINT Check_HTThanhtoan CHECK ( [HTThanhToan] IN ('Ví momo','Chuyển khoản ngân hàng','Thanh toán khi nhận hàng'))

ALTER TABLE DONHANG
ADD CONSTRAINT Check_NGAY CHECK ( NGLAP < NGAYGIAOTC)

ALTER TABLE DONHANG
ADD CONSTRAINT Check_GiaSPBD CHECK ( GiaSPBD >= 0 ) 
--bang CTDH
ALTER TABLE CTDH
ADD CONSTRAINT Check_SL CHECK ( SL>0)