CREATE DATABASE SANTHUONGMAI
GO
USE SANTHUONGMAI
GO

CREATE TABLE THANHVIEN (
    MATV char(6) PRIMARY KEY,
    TEN nvarchar(50),
    SDT char(10),
    NGAYTG smalldatetime,
    NGSINH smalldatetime,
    GMAIL varchar(50)
);

CREATE TABLE DVVC(
    MADV char(6) PRIMARY KEY,
    TEN nvarchar(50),
    DIACHI varchar(100),
	GIA MONEY
);

CREATE TABLE NVIENVC (
	MANV CHAR(6) primary key,
	TEN NVARCHAR(50),
	GTINH VARCHAR(3),
	SDT	CHAR(10),
	MADV char(6) FOREIGN KEY REFERENCES DVVC(MADV)
);

CREATE TABLE SHOP(
	MSHOP CHAR(6) PRIMARY KEY,
	TENSHOP	NVARCHAR(30),
	SDT	VARCHAR(10),
	DIACHI VARCHAR(50),
	NGLAP SMALLDATETIME,
	CHUSHOP	CHAR(6) FOREIGN KEY REFERENCES THANHVIEN(MATV)
);

CREATE TABLE NSX( 
	MNSX CHAR(6) PRIMARY KEY,
	TEN	NVARCHAR(50),
	NUOCSX	NVARCHAR(30)
);

CREATE TABLE SANPHAM(
	MASP CHAR(6) PRIMARY KEY,
	TEN	NVARCHAR(100),
	GIA	MONEY,
	CONGDUNG NVARCHAR(100),
	NSX	CHAR(6) FOREIGN KEY REFERENCES NSX(MNSX),
	DANHMUC NVARCHAR(50)
);

CREATE TABLE CTSP(
	MASP CHAR(6) FOREIGN KEY REFERENCES SANPHAM(MASP),
	MSHOP CHAR(6) FOREIGN KEY REFERENCES SHOP(MSHOP),
	PRIMARY KEY (MASP,MSHOP)
);

CREATE TABLE VoucherVC(
	MVCVC CHAR(6) PRIMARY KEY,
	CONGDUNG NVARCHAR(50),
	GIATRI INT,
	MADV CHAR(6) FOREIGN KEY REFERENCES DVVC(MADV)
);

CREATE TABLE VoucherShop(
	MVCS CHAR(6) PRIMARY KEY,
	CONGDUNG NVARCHAR(20),
	GIATRI INT,
	MSHOP CHAR(6) FOREIGN KEY REFERENCES SHOP
);

CREATE TABLE DONHANG(
	MADH CHAR(6) PRIMARY KEY,
	NGLAP smalldatetime,
	GiaSPBD	MONEY,
	DIACHI NVARCHAR(50),
	SDT	CHAR(10),
	NGAYGIAOTC	SMALLDATETIME,
	TENKH	NVARCHAR(50),
	HTThanhToan	NVARCHAR(30),
	GIASPCC	MONEY,
	GIAVCCC	MONEY,
	TONGTIEN	MONEY,
	VOUCHERVC	CHAR(6) FOREIGN KEY REFERENCES VoucherVC(MVCVC),
	VOUCHERSHOP	CHAR(6) FOREIGN KEY REFERENCES VoucherShop(MVCS),
	NGUOIDAT	CHAR(6) FOREIGN KEY REFERENCES THANHVIEN(MATV),
	SHOP	CHAR(6) FOREIGN KEY REFERENCES SHOP(MSHOP),
	DVVC	CHAR(6) FOREIGN KEY REFERENCES DVVC(MADV)
);

CREATE TABLE CTDH(
	MADH	CHAR(6) FOREIGN KEY REFERENCES DONHANG(MADH),
	MASP	CHAR(6) FOREIGN KEY REFERENCES SANPHAM(MASP),
	SL	INT,
	PRIMARY KEY(MADH,MASP)
);

CREATE TABLE CTVANCHUYEN (
	MANV	CHAR(6) FOREIGN KEY REFERENCES NVIENVC(MANV),
	MADH	CHAR(6) FOREIGN KEY REFERENCES DONHANG(MADH),
	NGAYGIAO	SMALLDATETIME,
	PRIMARY KEY (MANV,MADH,NGAYGIAO)
);

CREATE TABLE DonKhieuNaiHoanTien(
	MADON	CHAR(6) PRIMARY KEY,
	NGAYLAP	SMALLDATETIME,
	NGUOILAP CHAR(6) FOREIGN KEY REFERENCES THANHVIEN(MATV),
	SHOP CHAR(6) FOREIGN KEY REFERENCES SHOP(MSHOP),
	DONHANG	CHAR(6) FOREIGN KEY REFERENCES DONHANG(MADH),
	LYDO nvarchar(250)
);